include:
  - project: 'jayarba1/slack-notification'
    ref: main
    file: '/gitlab-ci-templates/slack-notification.yml'

variables:
  REPORTS_FOLDER: './reports'

stages: # List of stages for jobs, and their order of execution
  - slack

build-test: # This job runs in the build stage, which runs first.
  stage: build
  image: mcr.microsoft.com/playwright:focal
  before_script:
    - npm install
  script:
    - npm run test
  after_script:
    - npm run report-xml
  artifacts:
    when: always
    expire_in: 2 days
    reports:
      junit: ./reports/*.xml
    paths:
      - build
      - $REPORTS_FOLDER
